### PR TITLE
Bugfix of Multi-select rendering problems in Microsoft Edge

### PR DESCRIPTION
**Pull request by nastoychev**
Bugfix of Multi-select rendering problems in Microsoft Edge #712

https://github.com/wireui/wireui/assets/41673191/9e24043c-6b6f-48f8-ae46-249e733f500a

### CODE REVIEW

**Comment by nastoychev** [comment]
https://github.com/wireui/wireui/assets/41673191/fe6c2010-248d-4bb4-b585-4a85f02da310

**Comment by ph7jack** [comment]
@nastoychev 
Thanks for contributing. 
Please, delete the build assets from your PR. Only the wireui team is allowed to build them to prevent malicious code.

**Comment by nastoychev** [comment]
> @nastoychev Thanks for contributing. Please, delete the build assets from your PR. Only the wireui team is allowed to build them to prevent malicious code.

@PH7-Jack thanks, done. :)

**Review by ph7jack — APPROVED** [review]
Thanks for contributing

**Pull request merged**
