### PR TITLE
Support Livewire v3

### PR DESCRIPTION
**Pull request by joaopalopes24**

### CODE REVIEW

**Comment by devajmeireles** [comment]
Any idea when it will be released?

**Comment by joaopalopes24** [comment]
> Any idea when it will be released?

**Comment by joaopalopes24** [comment]
@devajmeireles Hi Aj, I am working in tests, I think I finish this weekend.

**Comment by vlados** [comment]
wow! you've done amazing work! thanks!!!

**Comment by thsteinmetz** [comment]
So glad you're keeping this alive with Livewire v3. Thanks for all your hard work!

**Comment by yasnaderi** [comment]
👏 Fantastic work, team! The library components you're developing are pure genius. Keep up the amazing work! 💪🚀

**Comment by ph7jack** [comment]
Hi everyone! 
We now have a branch ready for testing. We have fixed all failing tests. 🎉 💪🏼 
It's now compatible with Livewire v3. 
Unfortunately, we have dropped the Livewire v2 compatibility. It was really annoying to keep the compatibility with both versions.

I hope all of you start testing this version. 
Require this version in the composer:
```
composer require wireui/wireui:dev-support-livewire-v3
```

**Review by ph7jack — DISMISSED** [review]

**Comment by yasnaderi** [comment]
> Hi everyone! We now have a branch ready for testing. We have fixed all failing tests. 🎉 💪🏼 It's now compatible with Livewire v3. Unfortunately, we have dropped the Livewire v2 compatibility. It was really annoying to keep the compatibility with both versions.
> 
> I hope all of you start testing this version. Require this version in the composer:
> 
> ```
> composer require wireui/wireui:dev-support-livewire-v3
> ```

Yeah 🎉

image

**Comment by josepueblaphcs** [comment]
I have a fresh install of laravel with jetstream + livewire 3 and, after installling wire ui and config following the installation instructions, I run "npm run build" and got this error:

image

**Comment by joaopalopes24** [comment]
@josepueblaphcs I will go to test today.

**Comment by yasnaderi** [comment]
> I have a fresh install of laravel with jetstream + livewire 3 and, after installling wire ui and config following the installation instructions, I run "npm run build" and got this error:


Did you run 
`composer require wireui/wireui:dev-support-livewire-v3`

**Comment by josepueblaphcs** [comment]
> @josepueblaphcs I will go to test today.

thanks so much!

**Comment by josepueblaphcs** [comment]
> > I have a fresh install of laravel with jetstream + livewire 3 and, after installling wire ui and config following the installation instructions, I run "npm run build" and got this error:
> 
> Did you run `composer require wireui/wireui:dev-support-livewire-v3`

Yes

**Comment by joaopalopes24** [comment]
@josepueblaphcs The problem isn't with the WireUI. I tested here and it work normally.

**Comment by josepueblaphcs** [comment]
> 

Now is ok, I was doing wrong the configuration of the tailwind.config.js file. Now I'm testing the components and the only one that is not working for me is the modal.

**Comment by ph7jack** [comment]
> > 
> 
> Now is ok, I was doing wrong the configuration of the tailwind.config.js file. Now I'm testing the components and the only one that is not working for me is the modal.

Try again. Update the package via composer.

**Comment by ph7jack** [comment]
If someone finds a problem, reply here in this PR. We will fix it ASAP.
We're planning to create a release this Monday.

**Comment by josepueblaphcs** [comment]
> > > 
> > 
> > 
> > Now is ok, I was doing wrong the configuration of the tailwind.config.js file. Now I'm testing the components and the only one that is not working for me is the modal.
> 
> Try again. Update the package via composer.

thanks so much, now it's all working for me. The only thing that I had to do, but also on the previous version was replace the <x-dropdown-link> from the navigation menu from jetstream for <x-dropdown.item> from wireUI.
Not a big deal but to have in mind.

**Comment by thsteinmetz** [comment]
Just upgraded my side project with this latest branch. Everything is working as expected. Thank you so much.

**Comment by joaopalopes24** [comment]
@thsteinmetz It's good!

**Review by taqiussa — APPROVED** [review]
I think it is ready to launch support livewire v3

**Comment by qisthidev** [comment]
This week?

**Comment by ph7jack** [comment]
Hi everyone, it's now released. Check out the release [here](https://github.com/wireui/wireui/releases/tag/v1.18.0)

**Pull request merged**
