### PR TITLE
fix: translate select placeholder

### LINKED ISSUE #162: The text of the search placeholder is not localized
**Describe the bug**
The text of the placeholder is plaint text and therefore cannot be localized.

**To Reproduce**
Check line 123 in the select component:

` placeholder="Search here"`

**Expected behavior**
It would be nice if it can be added to the messages.php of each language and use the following code in the component e.g.:

`:placeholder=trans('wireui::messages.placeholder_search')`

### PR DESCRIPTION
**Pull request by REJack**
- already translated: en & de
- not translated: ar, bg, ca, es, fa, fr, it, nl_NL, pt_BR, ru & sk

Closes #162

### CODE REVIEW

**Comment by ph7jack** [comment]
@REJack can you translate the other langs? If no, no problems. 
Thanks so much for your contribution

**Comment by REJack** [comment]
I could try it with deepl or google translate, but I don't know if its correct 🤣

**Comment by ph7jack** [comment]
@REJack I would use google to translate hahaha

**Comment by REJack** [comment]
Ok, I will add the translations later. Can you give me the portuguese(pt_BR) translation? Then I don't have to embarrass myself 🤣

**Comment by REJack** [comment]
@PH7-Jack I've added the translations, may you can check if pt_BR is correct 😄

**Review by ph7jack — APPROVED** [review]

**Comment by ph7jack** [comment]
Thanks for this translation !!!

**Pull request merged**
