### PR TITLE
Add monday first day support

### LINKED ISSUE #226: datetimepicker first day of week
Hi
 it is possible for the first day of the week to be Monday?

### PR DESCRIPTION
**Pull request by haringsrob**
Hey 👋 ,

I could not find a way to set monday to be the first day of the week.

I think this implementation does the job.

See video for a demo
Screen Recording 2022-06-16 at 11 01 50
 (individual date pickers can have their own state.)

`<x-datetime-picker :monday-first-day="true"/>`

fixes #226 226

### CODE REVIEW

**Comment by ph7jack** [comment]
@haringsrob Thanks for contributing. The first day of the week is a great feature, but it's more complex than a boolean option to set only one day of the weekday. 
We need to have the ability to set any day as the first day of the week.

**Comment by haringsrob** [comment]
Hey @PH7-Jack,

You are right. I did some checking before but must have missed the very few cases where it is not Monday or Sunday.

I believe what would be the best way is to make use of this:

https://github.com/iamkun/dayjs/issues/215#issuecomment-1139442389

However, I have no idea of how to add this to the setup, it could be combined with a global setting or a per field property.

Thoughts?

**Comment by ph7jack** [comment]
@haringsrob Sure, the dayjs plugins can be used to create this feature if needed.

**Comment by ph7jack** [comment]
I'm closing this PR for now, we need a complete **first-day-of-week** solution to prevent futures break changes

**Pull request closed without merging**
