### PR TITLE
Toggle in dark mode does not change color

### PR DESCRIPTION
**Pull request by modrictin**
It does change it, but only slightly, it's not visible. I think this is way better.

Thanks,
Tin

### CODE REVIEW

**Comment by ph7jack** [comment]
Hi @modrictin 
I understand, but it's the expected behavior in dark mode. 
Toggle off: gray
Toggle on: white

Dark colors don't pretty together.
Thanks for contributing

**Comment by modrictin** [comment]
Hey @PH7-Jack ,

Thanks for letting me know!
Can you consider making the difference between states more visible? To me, both states look almost the same.

Thanks in advance,
Tin

image
image

**Comment by ph7jack** [comment]
@modrictin It's interesting. I'll think of a solution for that. Maybe just add a CSS class and anyone can override it with your color preference

**Comment by modrictin** [comment]
@PH7-Jack I can submit a PR if you give me few tips on how to do it so I don't mess up your flow

**Comment by nicolagianelli** [comment]
@PH7-Jack 
It would be nice to have.. I think the accent color for toggles, checkboxes and radios should be customizable to use primary color instead of secondary one, anyway thank you for this library!

**Comment by p08dev** [comment]
A workaround that works for me:

```css
.dark .peer:checked ~ .dark\:peer-checked\:bg-secondary-700 {
    background-color: #ff0000 !important;
}
```

**Pull request closed without merging**
