### PR TITLE
Base path configuration [critical bug]

### PR DESCRIPTION
**Pull request by alabacakmurat**
I was working on my test server which has also a subfolder installation of Laravel 9.x. WireUI didn't perform well on that environment compared to the main application. I figured out the route definitions for Laravel are quite okay but when it comes to fetching data called in js file, there is no base path configuration. That's why I quickly handled this problem maybe not in the best way.

This problem is definitely urgent to be fixed for subfolder usage.

image
image

### Also... [**NOT IN COMMITS YET**]
image

### CODE REVIEW

**Comment by ph7jack** [comment]
@alabacakmurat I'm not sure why it's a critical bug. Could you provide information about how you're creating a laravel application?
About your code, keep the default code formatting, and do not commit your IDE/project-related files, like .pnpm-debug.log, this project is using the Yarn as a node package manager, use it. 
Never commit the build assets, because these files are so long, we can't make a good review on them, and to prevent malicious code inside these files only the WireUI team can commit the build assets
Thanks for contributing

**Comment by alabacakmurat** [comment]
> 

I am not much of a git user and I didn't spend much with wire ui. These were the first errors I encountered in a few hours. I'll try my best next time. Well it is a critical bug/error because the dialog component for instance "fetches" its buttons and icons based on route definitions and a subfolder application of Laravel like '/my/path' blocks wire-ui from fetching its components because it tries to retrieve them from the main base path '/wireui/icons[/...]' (not '/my/path/wireui/icons[/..]') so no icons and no buttons show up.

**Comment by ph7jack** [comment]
@alabacakmurat 
Maybe your server is not fully configured to run laravel in a subdirectory, the wireui will use the laravel base URL. 
your subfolder path doesn't appear in the URL

I think if your change the APP_URL the route will be fixed

Try something like it on your server
https://laravel-news.com/subfolder-install
https://lucabecchetti.medium.com/configure-laravel-to-work-in-a-subdirectory-and-with-artisan-serve-at-the-same-time-654ba0c1fd0b
https://laravel.io/forum/09-08-2015-deploy-laravel-51-on-a-subdirectory

**Comment by alabacakmurat** [comment]
@PH7-Jack 

I checked the base code. As far as I remember component ts files were using relative path with Fetch API, but thanks anyway

**Comment by ph7jack** [comment]
@alabacakmurat The url is relative to the laravel app url. How is your subfolder implementation?

**Comment by alabacakmurat** [comment]
@PH7-Jack Well yes but only when you build the assets yourself. The assets controller using the files under "dist" folder which is prebuilt with relative path pointing to "/" (assuming this is where your app based at)

I should have opened an issue rather an a PR

**Comment by ph7jack** [comment]
@alabacakmurat 
Could you create an issue to discuss it? 
See this site answering a question about the relative URL path.
https://stackoverflow.com/questions/36369082/relative-paths-with-fetch-in-javascript

The wireui uses a slash before the path to use the domain URL. 
As I said before, configure the folder location in your server, point it to the laravel folder

**Pull request closed without merging**
