### PR TITLE
Modified button to be a little nicer and add xs, sm, md, lg

### PR DESCRIPTION
**Pull request by putera**

### CODE REVIEW

**Comment by ph7jack** [comment]
@putera Thanks for your contribution! 
Can you add a "before" and "after" preview for this?

**Comment by putera** [comment]
> @putera Thanks for your contribution! Can you add a "before" and "after" preview for this?

Yes, sure.

Before :
Before

After :
After

**Review by ph7jack — APPROVED** [review]
@putera I'm so happy with your contribution. Sorry for the long time to merge this.

**Comment by PH7-Jack** [comment]
test

**Comment by putera** [comment]
Happy to contribute, i will try to edit the docs also and PR.

**Pull request merged**
