### PR TITLE
Update naming translation folder NL to work with L10 language syntax

### PR DESCRIPTION
**Pull request by NoahNxT**
Updating the name of the NL folder to work with L10 default naming for locales

### CODE REVIEW

**Comment by ph7jack** [comment]
@NoahNxT Please, provide a PR description or it will be closed.

**Comment by NoahNxT** [comment]
> @NoahNxT Please, provide a PR description or it will be closed.

Done

**Comment by ph7jack** [comment]
@NoahNxT Thank you. 
I'm not sure about the NL lang, where can I find this information?

**Comment by NoahNxT** [comment]
https://laravel.com/docs/10.x/localization

Like in the example lang folder names are normally just the lang code.

**Comment by ph7jack** [comment]
@NoahNxT Not all langs. For Portuguese Brazil, it has pt_BR. 
This lang file was sent to us for another contributor. So I don't know which name is the correct one.
The laravel documentation doesn't have any information about this. Could you send me another website to check this?
I want to understand it better

**Comment by NoahNxT** [comment]
Maybe just spin up a new L10 project and try it yourself?

**Comment by ph7jack** [comment]
Closing this PR. Wireui will not longer support translations by default.

**Pull request closed without merging**
