### PR TITLE
Added ability to add html elements to cornerHint

### PR DESCRIPTION
**Pull request by ettiennelouw**

### CODE REVIEW

**Comment by ph7jack** [comment]
@ettiennelouw Thanks for contributing, could you give more information about it?

**Comment by ettiennelouw** [comment]
Hi, instead of adding just a string, piece of text it would great to be able to add like a tailwind badge or span with some classes to it or even a heroicon. We use this on our back end systems and on some forms we save the data changed as drafts then we add a icon to the corner hint or a badge with 'undo' so that before you save you can undo the change to original value.

**Comment by ph7jack** [comment]
@ettiennelouw I understand what you are doing, but it's dangerous, we need to use the `{{ }}` to prevent XSS attacks
See the laravel documentation https://laravel.com/docs/9.x/blade#html-entity-encoding

However, I know how to do it without losing security, just pass the label as a slot instead of an attribute in the input component.
```
resources/views/components/input.blade.php

@if ($label)
    <x-dynamic-component
        :component="WireUi::component('label')"
        :has-error="$hasError"
        :for="$id"
    >
        {{ $label }}
    </x-dynamic-component>
@endif

@if ($cornerHint)
    <x-dynamic-component
        :component="WireUi::component('label')"
        :has-error="$hasError"
        :for="$id"
    >
        {{ $cornerHint }}
    </x-dynamic-component>
@endif
```

It will work
```
<x-input>
    <x-slot name="label">
        <b>AAAA</b>
    </x-slot>

    <x-slot name="cornerHint">
        <x-icon name="home" class="w-5 h-5" />
    </x-slot>
</x-input>
```

Do you understand it?  
Could you rollback your changes in the label component and apply the same thing in all wireui components that use the label?
Update the wireui docs too, adding information about how we can pass a slot HTML into the label

**Comment by ettiennelouw** [comment]
That is true, gave it a shot and all working as expected. I'm closing this.

**Pull request closed without merging**
