### PR TITLE
Add Tooltip Component

### PR DESCRIPTION
**Pull request by joaopalopes24**
The purpose of this PR is to add the tooltip component to the application. It will have the following options:

> `arrow: boolean - default(true)`
> `timeout: int|null - default(2000)`
> `message: string|null - default(null)`
> `placement: string - default('top')`
> `animation: string - default('scale')`
> `theme: string - default('translucent')`
> `trigger: string - default('mouseenter focus')`

Possible values ​​follow the [tippy.js](https://atomiks.github.io/tippyjs/) documentation. The `timeout` is set in milliseconds.

Examples:

You can use the magic method `$tooltip` with a default time of 2000ms.
```
<x-button x-on:click="$tooltip('Tooltip')" green>
    Test
</x-button>

<x-button x-on:click="$tooltip('Tooltip', 5000)" green>
    Test
</x-button>
```

Or you can use the directive when the trigger is `'mouseenter focus'`, with the default characteristics used in the component.
```
<x-button x-tooltip="Tooltip" green>
    Test
</x-button>
```

Or through the Tooltip component.
```
<x-tooltip message="Message here">
    <x-button x-on:click="dispatch" green>
        Test
    </x-button>
</x-tooltip>

<x-tooltip theme="material">
    <x-slot name="tooltip">
        <strong>Tooltip</strong>
    </x-slot>

    <x-button green>
        Test
    </x-button>
</x-tooltip>

<x-tooltip theme="light-border" trigger="manual" :timeout="null">
    <x-slot name="tooltip">
        <strong>Tooltip</strong>
    </x-slot>

    <x-button x-on:click="dispatch" green>
        Test
    </x-button>
</x-tooltip>
```

### CODE REVIEW

**Comment by joaopalopes24** [comment]
Any suggestion is always welcome.

**Comment by joaopalopes24** [comment]
Remembering that the tests are missing.

**Comment by tshafer** [comment]
Will this support embedded html?

**Comment by joaopalopes24** [comment]
@PH7-Jack Now it's time to think about the best solution for Tippy.js CSS.

**Comment by joaopalopes24** [comment]
@PH7-Jack I created the `@wireUiExternalStyles` directive for CSS from external packages.

This Eslint error is strange, apparently from the commit history it was due to the eslint update.

**Comment by joaopalopes24** [comment]
This feature is being redone.

**Pull request closed without merging**
