### PR TITLE
feat: add laravel 9 support (PHP8 only)

### PR DESCRIPTION
**Pull request by REJack**

### CODE REVIEW

**Comment by mtawil** [comment]
@REJack why did you remove PHP7.4 support?

**Comment by REJack** [comment]
> @REJack why did you remove PHP7.4 support?

PHP 7.4 is End of Live and will only get Security Updates till 28. Nov 2022 and Laravel 9 also dropped 7.4 support too, so it's the best choice to drop it too IMHO

**Comment by mtawil** [comment]
@PH7-Jack Any plans to support Laravel 9?

**Comment by ph7jack** [comment]
@mtawil Yes. I will create an official announcement about this. I have some news

**Review by ph7jack — APPROVED** [review]
Thanks a lot for this PR.

**Pull request merged**
