### PR TITLE
feat: improve select to add a custom slot in popover

### LINKED ISSUE #269: Can no longer slot custom html into select options
**Describe the bug**
Prior to the recent update that introduced the async select options, when using the slot options you could insert custom elements into the options list, for example you could add a button to the bottom of the list to allow the user to add a new entry.

**To Reproduce**
Put anything other than `<x-select.option>` or `<x-select.user-option>` inside the `<x-select>` element and it will be ignored. For example in the below code the `<div>` and `<x-button>` elements are now missing in the rendered output:

```
<x-select
    {{ $attributes }}
>
    @php
        $contacts = auth()->user()->company->contacts()
            ->where('user_id', '=', auth()->user()->id)
            ->orWhere('shared', '=', true)->get();
    @endphp
    <div class="text-ethos-gray p-2 w-full bg-slate-100">Internal Contacts</div>
    @foreach(auth()->user()->company->users as $user)
        <x-select.user-option
            img="{!! $user->profile_photo_url !!}"
            label="{{ $user->display_name }}"
            value='users:{{ $user->id }}'
        />
    @endforeach
    <div class="text-ethos-gray p-2 w-full bg-slate-100">External Contacts</div>
    @foreach($contacts as $contact)
        <x-select.user-option
            img="https://ui-avatars.com/api/?name={{urlencode($contact->name)}}&color=ffffff&background=bec923"
            label="{{ $contact->name }}"
            value='contacts:{{ $contact->id }}'
        />
    @endforeach
    <x-button class="w-full" label="Add Contact" icon="user-add" wire:click="$emit('openModal', 'modal.create-contact')" />
</x-select>
```

**Expected behavior**
I understand this was probably not intentional functionality however in the past this did work and would enable to customise the options extensively. For my use case I just need to be able to add headings and a button at the bottom of the options however I'm sure there are numerous other use-cases for being able to insert custom elements.

### PR DESCRIPTION
**Pull request by MarceloZapatta**
Hi!

This PR add a slot to pass any code you want in the options of the popover. This allow you to make something like this example below, passing a slot <x-slot name="customOptions">:

```
<x-select wire:model.defer="produto.categoria_id" placeholder="Selecione uma categoria" option-label="nome"
    :searchable="true" option-value="id"
    :options="$categorias->map(fn ($categoria) => ['nome' => $categoria->nome, 'id' => $categoria->id])">
    <x-slot name="customOptions">
        <hr>
        <li class="py-2 px-3 text-secondary-500 cursor-pointer"
            onclick="Livewire.emit('openModal', 'categoria.categoria-editar')">
            <i class="fa-solid fa-plus mr-2"></i> Adicionar categoria
        </li>
    </x-slot>
</x-select>
```

Captura de Tela 2022-06-09 às 23 48 31

### CODE REVIEW

**Comment by ph7jack** [comment]
@MarceloZapatta Thanks for contributing
Could you add two slots instead this one slot?

```
<x-slot name="prepend" /> // before options
<x-slot name="append" /> // after options

-----------

@isset ($prepend)
    {{ $prepend }}
@endisset
```

**Comment by MarceloZapatta** [comment]
> @MarceloZapatta Thanks for contributing Could you add two slots instead this one slot?
> 
> ```
> <x-slot name="prepend" /> // before options
> <x-slot name="append" /> // after options
> 
> -----------
> 
> @isset ($prepend)
>     {{ $prepend }}
> @endisset
> ```

Don't you think it would be a better name something like "prependOptions" or "prependPopover"?

**Comment by ph7jack** [comment]
> > @MarceloZapatta Thanks for contributing Could you add two slots instead this one slot?
> > ```
> > <x-slot name="prepend" /> // before options
> > <x-slot name="append" /> // after options
> > 
> > -----------
> > 
> > @isset ($prepend)
> >     {{ $prepend }}
> > @endisset
> > ```
> 
> Don't you think it would be a better name something like "prependOptions" or "prependPopover"?

Yes, it can be **beforeOptions** and **afterOptions**

**Comment by MarceloZapatta** [comment]
> > > @MarceloZapatta Thanks for contributing Could you add two slots instead this one slot?
> > > ```
> > > <x-slot name="prepend" /> // before options
> > > <x-slot name="append" /> // after options
> > > 
> > > -----------
> > > 
> > > @isset ($prepend)
> > >     {{ $prepend }}
> > > @endisset
> > > ```
> > 
> > 
> > Don't you think it would be a better name something like "prependOptions" or "prependPopover"?
> 
> Yes, it can be **beforeOptions** and **afterOptions**

Done

**Review by ph7jack — APPROVED** [review]
Great job, thanks a lot

**Pull request merged**
